name: build-installer
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@master
        with:
          repository: ste2425/psp-consolizer-installer
          path: installer
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:samd

      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:samd:nano_33_iot main/software/PSP-Bluetooth-Controller -e

      - name: install installer
        run: yarn
        working-directory: installer

      - name: package
        run: yarn package
        working-directory: installer

      - name: list directories
        run: dir
        working-directory: installer
