name: build-installer
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Bluepad 32
        uses: robinraju/release-downloader@v1.5
        with:
          repository: ricardoquesada/bluepad32
          tag: release_v3.5.1
          fileName: bluepad32-nina-v3.5.1.tar.gz
          out-file-path: bluepad

      - name: Extract Bluepad
        run: tar -xvzf bluepad32-nina-v3.5.1.tar.gz
        working-directory: bluepad

      - uses: actions/checkout@v3
        name: checkout PSP-consolizer
        with:
          path: main

      - uses: actions/checkout@master
        name: Checkout installer
        with:
          repository: ste2425/psp-consolizer-installer
          path: installer

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:samd

      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:samd:nano_33_iot software/PSP-Bluetooth-Controller -e
        working-directory: main

      - name: Run yarn install
        run: yarn
        working-directory: installer

      - name: Copy binaries
        run: |
          copy main\software\PSP-Bluetooth-Controller\build\arduino.samd.nano_33_iot\PSP-Bluetooth-Controller.ino.bin installer\PSP-Bluetooth-Controller.ino.bin
          copy bluepad\bluepad32-nina-v3.5.1\bluepad32-nina-full-v3.5.1.bin installer\bluepad32-nina.bin

      - name: Run yarn package
        run: yarn package
        working-directory: installer

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Installer
          path: installer/build
