name: Build-PSP-Bluetooth
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-arduino-cli@v1
        name: Install Arduino CLI
      - uses: actions/checkout@v3
        name: checkout PSP-Bluetooth
        with:
          path: develop
      - name: Install Dependencies
        run: ./install.sh
        working-directory: develop/software/scripts
      - name: Build
        run: arduino-cli compile --log --fqbn esp32-bluepad32:esp32:esp32 --output-dir ../bin ../
        working-directory: develop/software/scripts
