name: Build-PSP-Bluetooth
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-arduino-cli@v1
        name: Install Arduino CLI
      - uses: actions/checkout@v3
        name: checkout PSP-Bluetooth
        with:
          path: develop
      - name: Install Dependencies
        run: ./install.sh
        working-directory: develop/software/scripts
      - name: Build
        run: arduino-cli compile --log --fqbn esp32-bluepad32:esp32:esp32 --output-dir ../bin --additional-urls "https://raw.githubusercontent.com/ricardoquesada/esp32-arduino-lib-builder/master/bluepad32_files/package_esp32_bluepad32_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json" ../
        working-directory: develop/software/scripts
