name: Build-PSP-Bluetooth
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-arduino-cli@v1
        name: Install Arduino CLI
      - uses: actions/checkout@v3
        name: checkout PSP-Bluetooth
        with:
          path: develop
      - name: Install Dependencies
        run: ./install.sh
        working-directory: develop/software/scripts
        env:
          GITHUB_ACTION: true
      - name: Build
        run: ./compile.sh
        working-directory: develop/software/scripts
        env:
          GITHUB_ACTION: true
      - name: Merge binaries
        run: ./merge.sh
        working-directory: develop/software/scripts
        env:
          GITHUB_ACTION: true
      - uses: actions/upload-artifact@v4
        with:
          name: binFolder
          path: develop/software/bin/
      - uses: actions/upload-artifact@v4
        with:
          name: pspBluetooth.bin
          path: develop/software/bin/merged-firmware.bin
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: pspBluetooth.bin
          prerelease: true
          name: PSP Bluetooth [Internal] [Develop]
          generate_release_notes: true
