name: build-installer
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout PSP-consolizer
        with:
          path: main

      - uses: actions/checkout@master
        name: Checkout installer
        with:
          repository: ste2425/psp-consolizer-installer
          path: installer

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:samd

      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:samd:nano_33_iot software/PSP-Bluetooth-Controller -e
        working-directory: main

      - name: Run yarn install
        run: yarn
        working-directory: installer

      -name: Copy PSP Consolizer binary
        run: copy main\software\PSP-Bluetooth-Controller\build\arduino.samd.nano_33_iot\PSP-Bluetooth-Controller.ino.bin installer\

      - name: Run yarn package
        run: yarn package
        working-directory: installer
